package game

import (
	"log"
	"math/rand/v2"

	"github.com/google/uuid"
)

type position = int

type size struct {
	x position
	y position
}

var Settings = struct {
	TickRate    uint8
	FieldSize   size // dimensions of the field
	SpriteSize  size
	PlayerSpeed position // pixels traveled per tick
}{
	TickRate:    60,
	FieldSize:   size{600, 600}, // TODO: share with client
	SpriteSize:  size{100, 100},
	PlayerSpeed: 7,
}

////////////////////////////////////////////////////////////////////////////////

type PlayerId = string

type Player struct {
	Id     PlayerId `json:"id"`
	Color1 uint32   `json:"color1"` // 0x 00 FF FF FF -> most significant pair = 00 for 24 bit color.
	Color2 uint32   `json:"color2"` // if most signficant pair is used, least signficant pair becomes opacity
	Color3 uint32   `json:"color3"`
	X      position `json:"x"`
	Y      position `json:"y"`
}

func NewPlayer() *Player {
	return &Player{
		Id:     uuid.New().String(),
		Color1: rand.Uint32() >> 8,
		Color2: rand.Uint32() >> 8,
		Color3: rand.Uint32() >> 8, // opacity is defined on client
		X:      0,
		Y:      0,
	}
}

type players = map[PlayerId]*Player

////////////////////////////////////////////////////////////////////////////////

type timestamp = uint64

type inputState struct {
	Up    bool `json:"up"`
	Down  bool `json:"down"`
	Left  bool `json:"left"`
	Right bool `json:"right"`
}

// Generated by the game engine,
type GameEvent struct {
	TimestampMs timestamp  `json:"timestampMs"`
	PlayerId    PlayerId   `json:"playerId"`
	InputState  inputState `json:"inputState"`
}

////////////////////////////////////////////////////////////////////////////////

type Game struct {
	Players players `json:"players"`
}

func New() *Game {
	return &Game{
		Players: players{},
	}
}

func (g *Game) AddPlayer(p *Player) {
	g.Players[p.Id] = p
	// DEBUG
	log.Println("Added player:", p.Id)
}

func (g *Game) RemovePlayer(playerId PlayerId) {
	delete(g.Players, playerId)
	// DEBUG
	log.Println("Removed player:", playerId)
}

/*
Set the fields of Game, given a queue of GameEvents
TODO: pre-sort inputs?
TODO: sprite:sprite collision detection
*/
func (g *Game) Update(e GameEvent) {
	player := g.Players[e.PlayerId]
	speed := Settings.PlayerSpeed
	fieldSize := Settings.FieldSize
	spriteSize := Settings.SpriteSize

	// NOTE: inverted directions like css
	if e.InputState.Up {
		player.Y = max(player.Y-speed, 0)
	}
	if e.InputState.Down {
		player.Y = min(player.Y+speed, fieldSize.y-spriteSize.y)
	}
	if e.InputState.Left {
		player.X = max(player.X-speed, 0)
	}
	if e.InputState.Right {
		player.X = min(player.X+speed, fieldSize.y-spriteSize.y)
	}
}
